### ISSUE TITLE
The `testLoadRules` fails depending on the order of execution

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-mqtt-bridge#14]
The test `testLoadRules` in the `MappingRulesLoaderTest` class can fail depending on the order when it's executed.
If it runs first everything works fine, but if it runs after the `testInitMoreThanOnce`, it fails.
This is because the usage of singleton in `MappingRulesLoader` which is of course "shared" across tests.
If `testInitMoreThanOnce` runs first, it initialize the loader so the `testLoadRules` will fail.

**Comment by ppatierno** [comment]
@antonio-pedro99 can you take a look at this, please?

**Comment by antonio-pedro99** [comment]
@ppatierno #15 fixes this issue.
